version: '3.7'

services:
  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/var/www/beer-menu/key/key.json
    volumes:
      - .:/var/www/beer-menu
